AWSTemplateFormatVersion: 2010-09-09
Parameters:
    Instancetype:
        Description: EC2 instance type selection
        Type: String
        Default: t2.micro
        AllowedValues: 
            - t2.micro
            - t2.medium
            - t2.small
            - m4.large
    
Resources:
    EC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-0dfcb1ef8550277af
            InstanceType: !Ref Instancetype
            SecurityGroups:
                - !Ref InstanceSecurityGroup
                - !Ref InstanceHTTPSecurityGroup
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    sudo yum update -y
                    sudo amazon-linux-extras install -y php7.4
                    sudo yum install -y httpd
                    sudo systemctl start httpd
                    sudo systemctl enable httpd
                    sudo usermod -a -G apache ec2-user
                    sudo chown -R ec2-user:apache /var/www
                    sudo chmod 2775 /var/www && find /var/www -type d -exec sudo chmod 2775 {} \;
                    find /var/www -type f -exec sudo chmod 0664 {} \;
                    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                    php wp-cli.phar — info
                    chmod +x wp-cli.phar
                    sudo mv wp-cli.phar /usr/local/bin/wp
                    wp — info
                    cd /var/www/html 
                    wp core download
            
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable SSH via port 22
            SecurityGroupIngress:
                - CidrIp: 0.0.0.0/0
                  IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
    InstanceHTTPSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable HTTP via port 80
            SecurityGroupIngress:
                - CidrIp: 0.0.0.0/0
                  IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
    
Outputs:
    InstanceID:
        Description: Instacne ID of the instance created
        Value: !Ref EC2Instance
    PublicDNS:
        Description: Get public DNS name
        Value: !GetAtt
                - EC2Instance
                - PublicDnsName
    PublicIP:
        Description: Get public IP address
        Value: !GetAtt
                - EC2Instance
                - PublicIp